### ISSUE TITLE
test/dev setup

### ISSUE THREAD

**Issue by plebhash** [GPTechinno/bm13xx-rs#1]
just found this repo, quite interesting!

I'm curious to know what kind of setup is being used to drive development for this project?

**Comment by Georges760** [comment]
At the beginning of Bitaxe project I reversed most of the BM1397 communication protocol using a Saleae and Ghidra, then Bitaxe became what it is today, with support up to the latest BM1370. I am working on a pure Rust based FW for Bitaxe, so this crate is the ASIC building block. That's why I am also interested into allowing Sv2 based crate to be really no_std...

**Comment by plebhash** [comment]
that's pretty cool!

yeah I see you have a fork of `esp-hal` so I assumed it was related to the BitAxe, but it also got me curious about the possibilities of experimenting with a bitcrane on bigger hashboards

**Comment by Georges760** [comment]
No problem, in this crate, I added some examples that communicate to ASIC using a linux tty, so it can be done on linux environment (that's what I did to dump all ASIC register default values..)
